client/src/App.jsx
client/src/Components/About.js
client/src/Components/Cards.js
client/src/Components/Carousel.js
client/src/Components/Home.js
client/src/Components/HomeBanner.js
client/src/Components/Nav.jsx
client/src/Components/PetDetail.js
package.json
server.js
yarn.lock

Closes #5. Added pictures to About Us

Enhancement 5 components

---

client/src/Components/Cards.js
package.json
yarn.lock

Closes #7   Created cards for animal display then made another commit because photos where being pulled from the small quality stock photos rather than the full, reducing the quality of dog photos.

Enhancement cards 7 elias

---

client/src/App.css
client/src/App.jsx
client/src/Components/Nav.jsx
client/src/Components/Pets.js

closes #enhancement-12-static-navbar

made nav bar static by using className and Link to

---

client/src/App.css
client/src/Components/Cards.js
client/src/Components/Carousel.js
client/src/Components/Dogs.js
server.js

closes #15 
Adding carousel links and corrected banner styling

carousel links/home component styling

---

client/src/App.css
client/src/App.jsx
client/src/Components/Cards.js
client/src/Components/Carousel.js
client/src/Components/Cats.js
client/src/Components/Dogs.js
server.js

closes #19 
Added cat and dog components, which link to navbar and carousel.
Card component is attached, however still need to be filtered for each category

Enhancement 19 cat and dog components

---

client/src/Components/Cards.js

closes #enhancement-17-no-stock-pictures
The following code was added:
{pets && pets.map((pets, index) => {
if (pets.photos.length>0 && pets.photos[0].full)
And the following lines were modified to match the nomenclature

only display pet posts that include pictures

---

client/src/Components/Cats.js
client/src/Components/Dogs.js

Kind of closes #enhancement-24-filter-cats-and-dogs. 
I am pushing so my team members can get the code and replicate for the rest of the animal types.

Filtered only cats and dogs so team can work on the rest of the animals

---

client/src/Components/Cards.js
client/src/Components/Cats.js
client/src/Components/Dogs.js

Filter by agegroups

---

client/src/Components/About.js
client/src/Components/Cards.js
client/src/Components/Pets 2.js

closes #29 
enhancement-29-basic-filters

basic filters for age, size, and gender

---

client/src/App.jsx

added Home back to router

---

client/src/Components/Cards.js
client/src/Components/Dogs.js

Age-Sex-Size filters have to be re-added

adding filters again because they all disappeared 

---

client/src/App.jsx

adoptnow bug

---

client/README.md

added content to ReadMe 

---

client/src/Components/About.js
client/src/Components/Cards.js
client/src/Components/Pet_Components/Birds.js
client/src/Components/Pet_Components/Ferrets.js
client/src/Components/Pet_Components/Fish.js
client/src/Components/Pet_Components/Rabbits.js
client/src/Components/Pet_Components/Reptiles.js
client/src/Components/Pet_Components/Rodents.js

Added our personal sentences to the about me page

---

server.js

Server API call Fix

---

client/src/Components/Cards.js
client/src/Components/Pet_Components/Birds.js
client/src/Components/Pet_Components/Cats.js
client/src/Components/Pet_Components/Dogs.js
client/src/Components/filter.js

fully functional filters without styling

---

client/src/Components/Cards.js
server.js

closes #50 .
Tristan closed this issue on my laptop because he was having issues in his.

Tristan's token server API token server fetch fixx

---

client/src/Components/Carousel.js

fixed the carousel routes

---

client/src/Components/Carousel.js

Name now properly match routes to components

fixing naming conventions for routes

---

client/src/Components/Cards.js

Fixes issue with cards and brings  back more filtering options

Fixes issue with cards and brings  back more filtering options

---

.env.sample
client/src/Components/Cards.js
client/src/Components/Nav.jsx
server.js

added ENV , add muliteply get params from api side

---

client/src/Components/Nav.jsx

Please do not accept if it causes conflicts. I don't want anyone to lose their progress. 
closes #74

navbar options reduced due to API data limitations

---

client/public/index.html
client/src/App.css

card styling update

---

client/src/Components/Nav.jsx
client/src/Components/filter.js

removed the .link from the nav.links in nav.jsx

---

client/src/Components/Pet.js

fixed link to Petdetails

---

client/package.json
client/src/Animation/animation.jsx
client/src/Components/Pet.js
client/yarn.lock

re submitting rene's styling due to github issue

---

README.md

Upates to README
